## Pytorch Exercises 2
  
### Pytorch Tensor Exercises

In [1]:
# import pytorch library
import torch

##### 01. Tensor shaping (.reshape())

In [2]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

print(x.size())

torch.Size([3, 2, 2])


In [3]:
# reshape() don't save the results in the memory
print(x.reshape(-1)) # -1 : vectorization
print(x.reshape(12)) # 12 = 3*2*2

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [4]:
print(x.reshape(3, 4)) # 3*4 = 3*2*2
print(x.reshape(3, -1)) # dim1 = 3, dim2 = auto

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [5]:
print(x.reshape(3, 1, 4)) # 3*1*4 = 3*2*2
print(x.reshape(-1, 1, 4)) # fixed = dim2,3, auto = dim1

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [6]:
print(x.reshape(3, 2, 2, 1)) # 3*2*2*1 = 3*2*2

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


##### 02. Squeeze (remove dimension which has only one element)

In [7]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]]])
print(x.size())

torch.Size([1, 2, 2])


In [8]:
# all results are the same
print('default',x.squeeze().size())
print('choose the index',x.squeeze(0).size())
print()

# there is no change for the dim. of Tensor
# 'just only one element'
print(x.squeeze(1))
print(x.squeeze(2))

default torch.Size([2, 2])
choose the index torch.Size([2, 2])

tensor([[[1., 2.],
         [3., 4.]]])
tensor([[[1., 2.],
         [3., 4.]]])


##### 03. Unsqueeze (insert dimension (one) at certain index)

In [9]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]])
print(x.size())

torch.Size([2, 2])


In [10]:
# all results are the same
print(x.unsqueeze(2).size())
print(x.unsqueeze(-1).size())
print(x.reshape(2, 2, -1).size())

torch.Size([2, 2, 1])
torch.Size([2, 2, 1])
torch.Size([2, 2, 1])


##### 04. Indexing and slicing

In [11]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])
print(x.size())

torch.Size([3, 2, 2])


In [30]:
print(x[2])
print(x[-1])
print(x[2,:])
print(x[2,:,:])
print(x[2,0,1])
print(x[0,0:1,:])

tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor(10.)
tensor([[1., 2.]])


##### 05. split (split tensor to desiable shapes)

In [34]:
x = torch.FloatTensor(10, 4)
x.size()

torch.Size([10, 4])

In [41]:
splits = x.split(4, dim=0) # dim 1 (row)
print('splits length: ',len(splits))
print('splits type: ',type(splits))
print()
for s in splits:
    print(s.size()) # dim1 = 10 = 4+4+2

splits length:  3
splits type:  <class 'tuple'>

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


##### 06. chunk (split tensor to number of chunks)

In [42]:
x = torch.FloatTensor(8, 4)

In [48]:
chunks = x.chunk(3, dim=0)
print('chunks length: ',len(chunks))
print('chunks type: ',type(chunks))
print()
for c in chunks:
    print(c.size()) # dim1 = 8 = 3+3+2

chunks length:  3
chunks type:  <class 'tuple'>

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 4])


##### 07. index_select (select elements by using dimension index)

In [49]:
x = torch.FloatTensor([[[1, 1],
                        [2, 2]],
                       [[3, 3],
                        [4, 4]],
                       [[5, 5],
                        [6, 6]]])
indice = torch.LongTensor([2, 1])

print(x.size())

torch.Size([3, 2, 2])


In [51]:
y = x.index_select(dim=0, index=indice) # dim = 0 ->> means dim 1

# 1st of dim 1 -> index 2 of x
# 2st of dim 1 -> index 1 of x
# 3st of dim 1 -> none

print(y)
print(y.size())

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])
torch.Size([2, 2, 2])


##### 08. cat (concatenation of multiple tensors in the list)

In [52]:
x = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]])

print(x.size(), y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [53]:
# similar to create a block matrix.
z = torch.cat([x, y], dim=0) # concatenation of x and y at dim 1
print(z)
print(z.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([6, 3])


In [54]:
z = torch.cat([x, y], dim=-1) # end dim.
print(z)
print(z.size())

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


##### 09. stack (stacking of multiple tensors in the list)

In [55]:
# stacking the matrix
z = torch.stack([x, y]) # Tensor which have two 3x3 matrices
print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


In [56]:
z = torch.stack([x, y], dim=-1) # end dim.
print(z)
print(z.size())

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])
torch.Size([3, 3, 2])


##### Implement 'stack' function by using 'cat'.

In [57]:
# this is the same as: z = torch.stack([x, y])
# x.unsqueeze(0).size() = ([1,3,3])
# y.unsqueeze(0).size() = ([2,3,3])

z = torch.cat([x.unsqueeze(0), y.unsqueeze(0)], dim=0)
print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


##### Useful trick: merge results from iterations

In [68]:
result = []
for i in range(5):
    x = torch.FloatTensor(2, 2) # create a tensor which have the size of ([2,2])
    result += [x]
    
for j in result: # the list 'result' have 5 elements as tensor
    print(j)

result = torch.stack(result) # one tensor which have the size of ([5,2,2])
result.size()

tensor([[5.4367e+22, 1.0739e-05],
        [7.9963e+20, 1.0413e-11]])
tensor([[ 1.2612e-44,  0.0000e+00],
        [ 0.0000e+00, -8.5899e+09]])
tensor([[ 6.9874e-26, -2.0005e+00],
        [ 0.0000e+00, -8.5899e+09]])
tensor([[7.4269e-44, 8.1275e-44],
        [7.1466e-44, 7.0065e-44]])
tensor([[ 0.0000e+00, -8.5899e+09],
        [ 0.0000e+00, -8.5899e+09]])


torch.Size([5, 2, 2])