## Pytorch Exercises 1
  
### Pytorch Tensor Exercises

In [1]:
# import pytorch library
import torch

#### 01. Tensor allocation

In [2]:
## create tensor (3 types)

# Float Tensor (float)
ft = torch.FloatTensor([[1,2],
                        [3,4]])
print('* float tensor (float elements) :\n\n',ft)

# Long Tensor (integer)
lt = torch.LongTensor([[1,-2],
                       [-3,4]])
print('\n* long tensor (integer elements) :\n\n',lt)

# Byte Tensor (positive integer)
bt = torch.ByteTensor([[1,-2],
                       [-3,4]])
print('\n* byte tensor (positive integer elements) :\n\n',bt)

* float tensor (float elements) :

 tensor([[1., 2.],
        [3., 4.]])

* long tensor (integer elements) :

 tensor([[ 1, -2],
        [-3,  4]])

* byte tensor (positive integer elements) :

 tensor([[  1, 254],
        [253,   4]], dtype=torch.uint8)


#### 02. Tensor preallocation (random value)

In [3]:
## pre-allocation
# 특정 shape를 갖는 임의의 tensor를 생성하고 싶을 때 주로 사용
# torch.FloatTensor(dim1,dim2,dim3,...)
x = torch.FloatTensor(5,5)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 1.8788e+31, 1.7220e+22, 9.6695e-06],
        [2.6075e-09, 1.3096e-11, 2.0451e+20, 3.3586e-06, 6.4900e-10],
        [1.0477e+21, 2.1864e+23, 8.2288e-10, 2.3053e-12, 1.1495e+24],
        [3.0881e+29, 2.5226e-18, 4.2330e+21, 1.6534e+19, 1.1625e+27],
        [2.3329e-18, 4.5447e+30, 7.0062e+22, 1.2853e+31, 4.4765e+27]])


#### 03. NumPy compatibility

In [4]:
import numpy as np

# numpy array
x = np.array([[1,2],
              [3,4]])
print('* original numpy\n\n',x)

# the tensor using numpy array
xt = torch.from_numpy(x)
print('\n* tensor from numpy\n\n',xt)

# the pure tensor
tx = torch.LongTensor([[1,2],
                       [3,4]])
print('\n* original tensor\n\n',tx)

# convert the pure tensor to numpy array
ntx = tx.numpy()
print('\n* numpy from tensor\n\n',ntx)

* original numpy

 [[1 2]
 [3 4]]

* tensor from numpy

 tensor([[1, 2],
        [3, 4]])

* original tensor

 tensor([[1, 2],
        [3, 4]])

* numpy from tensor

 [[1 2]
 [3 4]]


#### 04. Tensor type-casting

In [5]:
print(ft,'\n\n',ft.long())

tensor([[1., 2.],
        [3., 4.]]) 

 tensor([[1, 2],
        [3, 4]])


In [6]:
print(lt,'\n\n',lt.float())

tensor([[ 1, -2],
        [-3,  4]]) 

 tensor([[ 1., -2.],
        [-3.,  4.]])


In [7]:
print(torch.FloatTensor([[-1,2],[-3,4]]).byte())

tensor([[255,   2],
        [253,   4]], dtype=torch.uint8)


#### 05. Tensor shape

In [8]:
t = torch.FloatTensor(7,3)

print('* tensor shape:\n',t.shape)
print('\n* tensor shape (slicing):\n',t.shape[0])
print('\n* tensor size (== shape):\n',t.size())
print('\n* tensor dimension (== len(shape)):\n',t.dim())


* tensor shape:
 torch.Size([7, 3])

* tensor shape (slicing):
 7

* tensor size (== shape):
 torch.Size([7, 3])

* tensor dimension (== len(shape)):
 2


#### 06. Element-wise operations

In [9]:
a = torch.FloatTensor([[1, 2],
                       [3, 4]])
b = torch.FloatTensor([[2, 2],
                       [3, 3]])

In [10]:
# element-wise operations
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a == b)
print(a != b)
print(a ** b)

tensor([[3., 4.],
        [6., 7.]])
tensor([[-1.,  0.],
        [ 0.,  1.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])
tensor([[False,  True],
        [ True, False]])
tensor([[ True, False],
        [False,  True]])
tensor([[ 1.,  4.],
        [27., 64.]])


#### 07. Inplace operations

In [11]:
print(".mul() don't save the result\n")
print(a.mul(b))
print(a)
print()
print(".mul_() saves the result\n")
print(a.mul_(b))
print(a)

.mul() don't save the result

tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])

.mul_() saves the result

tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


#### 08. Aggregation functions (Dimension reducing operations)

In [12]:
x = torch.FloatTensor([[1,2],
                       [3,4]])
# note)
# axis = 0 -> dim1
# axis = 1 -> dim2
# axis = -1 -> auto
print(x.sum())
print(x.mean())
print(x.sum(axis = 0))
print(x.mean(axis = -1))

# other aggregation functions
print(x.std())
print(x.var())
print(x.min())
print(x.max())

tensor(10.)
tensor(2.5000)
tensor([4., 6.])
tensor([1.5000, 3.5000])
tensor(1.2910)
tensor(1.6667)
tensor(1.)
tensor(4.)


#### 09. Broadcast in operations
Broadcast feature provides operations between different shape of tensors.

In [13]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[4, 8]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([1, 2])


In [14]:
z = x+y
print(z)
print(z.size())

tensor([[ 5., 10.]])
torch.Size([1, 2])


##### Tensor + Scalar

In [15]:
x = torch.FloatTensor([[1,2],
                       [3,4]])
c = 2

z = c + x
print(z)
print(z.size())

tensor([[3., 4.],
        [5., 6.]])
torch.Size([2, 2])


##### Tensor + Vector

In [16]:
v = torch.FloatTensor([1,
                       1])
z = v + x
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


##### Tensor + Tensor

In [17]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3],
                       [5]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([2, 1])


In [18]:
# x(1,1~2) + y(1,1)
# x(1,1~2) + y(2,1)
z = x + y
print(z)
print(z.size())

tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


##### Failure Case

In [19]:
# 차원이 다른 경우 scalar 차원의 'Tensor'만 연산 가능
x = torch.FloatTensor([[[1, 2],
                        [4, 8]]])
y = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print(x.size())
print(y.size())

z = x + y

torch.Size([1, 2, 2])
torch.Size([3, 3])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2